/**
 * Generated by Scrooge
 *   version: 4.5.0
 *   rev: 014664de600267b36809bbc85225e26aec286216
 *   built at: 20160203-205352
 */
package thrift

import java.util.Arrays

import com.twitter.finagle.Thrift
import com.twitter.finagle.stats.{NullStatsReceiver, StatsReceiver}
import com.twitter.scrooge.{TReusableMemoryTransport, ThriftStruct}
import com.twitter.util.{Future, Return, Throw, Throwables}
import org.apache.thrift.TApplicationException
import org.apache.thrift.protocol._
import org.apache.thrift.transport.TMemoryInputTransport

import scala.collection.mutable.{ArrayBuffer => mutable$ArrayBuffer, HashMap => mutable$HashMap}
import scala.language.higherKinds


@javax.annotation.Generated(value = Array("com.twitter.scrooge.Compiler"))
class DemoService$FinagleService(
  iface: DemoService[Future],
  protocolFactory: TProtocolFactory,
  stats: StatsReceiver,
  maxThriftBufferSize: Int,
  serviceName: String
) extends com.twitter.finagle.Service[Array[Byte], Array[Byte]] {
  import DemoService._

  def this(
    iface: DemoService[Future],
    protocolFactory: TProtocolFactory,
    stats: StatsReceiver,
    maxThriftBufferSize: Int
  ) = this(iface, protocolFactory, stats, maxThriftBufferSize, "DemoService")

  def this(
    iface: DemoService[Future],
    protocolFactory: TProtocolFactory
  ) = this(iface, protocolFactory, NullStatsReceiver, Thrift.maxThriftBufferSize)

  private[this] val tlReusableBuffer = new ThreadLocal[TReusableMemoryTransport] {
    override def initialValue() = TReusableMemoryTransport(512)
  }

  private[this] def reusableBuffer: TReusableMemoryTransport = {
    val buf = tlReusableBuffer.get()
    buf.reset()
    buf
  }

  private[this] val resetCounter = stats.scope("buffer").counter("resetCount")

  private[this] def resetBuffer(trans: TReusableMemoryTransport): Unit = {
    if (trans.currentCapacity > maxThriftBufferSize) {
      resetCounter.incr()
      tlReusableBuffer.remove()
    }
  }

  protected val functionMap = new mutable$HashMap[String, (TProtocol, Int) => Future[Array[Byte]]]()

  protected def addFunction(name: String, f: (TProtocol, Int) => Future[Array[Byte]]) {
    functionMap(name) = f
  }

  protected def exception(name: String, seqid: Int, code: Int, message: String): Future[Array[Byte]] = {
    try {
      val x = new TApplicationException(code, message)
      val memoryBuffer = reusableBuffer
      try {
        val oprot = protocolFactory.getProtocol(memoryBuffer)

        oprot.writeMessageBegin(new TMessage(name, TMessageType.EXCEPTION, seqid))
        x.write(oprot)
        oprot.writeMessageEnd()
        oprot.getTransport().flush()
        Future.value(Arrays.copyOfRange(memoryBuffer.getArray(), 0, memoryBuffer.length()))
      } finally {
        resetBuffer(memoryBuffer)
      }
    } catch {
      case e: Exception => Future.exception(e)
    }
  }

  protected def reply(name: String, seqid: Int, result: ThriftStruct): Future[Array[Byte]] = {
    try {
      val memoryBuffer = reusableBuffer
      try {
        val oprot = protocolFactory.getProtocol(memoryBuffer)

        oprot.writeMessageBegin(new TMessage(name, TMessageType.REPLY, seqid))
        result.write(oprot)
        oprot.writeMessageEnd()

        Future.value(Arrays.copyOfRange(memoryBuffer.getArray(), 0, memoryBuffer.length()))
      } finally {
        resetBuffer(memoryBuffer)
      }
    } catch {
      case e: Exception => Future.exception(e)
    }
  }

  final def apply(request: Array[Byte]): Future[Array[Byte]] = {
    val inputTransport = new TMemoryInputTransport(request)
    val iprot = protocolFactory.getProtocol(inputTransport)

    try {
      val msg = iprot.readMessageBegin()
      val func = functionMap.get(msg.name)
      func match {
        case _root_.scala.Some(fn) =>
          fn(iprot, msg.seqid)
        case _ =>
          TProtocolUtil.skip(iprot, TType.STRUCT)
          exception(msg.name, msg.seqid, TApplicationException.UNKNOWN_METHOD,
            "Invalid method name: '" + msg.name + "'")
      }
    } catch {
      case e: Exception => Future.exception(e)
    }
  }

  // ---- end boilerplate.

  private[this] val scopedStats = if (serviceName != "") stats.scope(serviceName) else stats
  private[this] object __stats_method1 {
    val RequestsCounter = scopedStats.scope("method1").counter("requests")
    val SuccessCounter = scopedStats.scope("method1").counter("success")
    val FailuresCounter = scopedStats.scope("method1").counter("failures")
    val FailuresScope = scopedStats.scope("method1").scope("failures")
  }
  addFunction("method1", { (iprot: TProtocol, seqid: Int) =>
    try {
      __stats_method1.RequestsCounter.incr()
      val args = Method1.Args.decode(iprot)
      iprot.readMessageEnd()
      (try {
        iface.method1()
      } catch {
        case e: Exception => Future.exception(e)
      }).flatMap { value: String =>
        reply("method1", seqid, Method1.Result(success = Some(value)))
      }.rescue {
        case e => Future.exception(e)
      }.respond {
        case Return(_) =>
          __stats_method1.SuccessCounter.incr()
        case Throw(ex) =>
          __stats_method1.FailuresCounter.incr()
          __stats_method1.FailuresScope.counter(Throwables.mkString(ex): _*).incr()
      }
    } catch {
      case e: TProtocolException => {
        iprot.readMessageEnd()
        exception("method1", seqid, TApplicationException.PROTOCOL_ERROR, e.getMessage)
      }
      case e: Exception => Future.exception(e)
    }
  })
  private[this] object __stats_method2 {
    val RequestsCounter = scopedStats.scope("method2").counter("requests")
    val SuccessCounter = scopedStats.scope("method2").counter("success")
    val FailuresCounter = scopedStats.scope("method2").counter("failures")
    val FailuresScope = scopedStats.scope("method2").scope("failures")
  }
  addFunction("method2", { (iprot: TProtocol, seqid: Int) =>
    try {
      __stats_method2.RequestsCounter.incr()
      val args = Method2.Args.decode(iprot)
      iprot.readMessageEnd()
      (try {
        iface.method2(args.a, args.b)
      } catch {
        case e: Exception => Future.exception(e)
      }).flatMap { value: Int =>
        reply("method2", seqid, Method2.Result(success = Some(value)))
      }.rescue {
        case e => Future.exception(e)
      }.respond {
        case Return(_) =>
          __stats_method2.SuccessCounter.incr()
        case Throw(ex) =>
          __stats_method2.FailuresCounter.incr()
          __stats_method2.FailuresScope.counter(Throwables.mkString(ex): _*).incr()
      }
    } catch {
      case e: TProtocolException => {
        iprot.readMessageEnd()
        exception("method2", seqid, TApplicationException.PROTOCOL_ERROR, e.getMessage)
      }
      case e: Exception => Future.exception(e)
    }
  })
  private[this] object __stats_method3 {
    val RequestsCounter = scopedStats.scope("method3").counter("requests")
    val SuccessCounter = scopedStats.scope("method3").counter("success")
    val FailuresCounter = scopedStats.scope("method3").counter("failures")
    val FailuresScope = scopedStats.scope("method3").scope("failures")
  }
  addFunction("method3", { (iprot: TProtocol, seqid: Int) =>
    try {
      __stats_method3.RequestsCounter.incr()
      val args = Method3.Args.decode(iprot)
      iprot.readMessageEnd()
      (try {
        iface.method3()
      } catch {
        case e: Exception => Future.exception(e)
      }).flatMap { value: Unit =>
        reply("method3", seqid, Method3.Result())
      }.rescue {
        case e => Future.exception(e)
      }.respond {
        case Return(_) =>
          __stats_method3.SuccessCounter.incr()
        case Throw(ex) =>
          __stats_method3.FailuresCounter.incr()
          __stats_method3.FailuresScope.counter(Throwables.mkString(ex): _*).incr()
      }
    } catch {
      case e: TProtocolException => {
        iprot.readMessageEnd()
        exception("method3", seqid, TApplicationException.PROTOCOL_ERROR, e.getMessage)
      }
      case e: Exception => Future.exception(e)
    }
  })
}